
CREATE TABLE public.device_type (
                                    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    name_device varchar NOT NULL,
                                    code varchar NULL,
                                    created_date date NOT NULL,
                                    updated_date date NOT NULL,
                                    "uuid" uuid NOT NULL,
                                    active bool NOT NULL,
                                    CONSTRAINT device_type_pk PRIMARY KEY (id)
);
-- public.diagnosis definition
-- Drop table
-- DROP TABLE public.diagnosis;
CREATE TABLE public.diagnosis (
                                  id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  failure varchar NOT NULL,
                                  "uuid" uuid NOT NULL,
                                  active bool NOT NULL,
                                  created_date date NOT NULL,
                                  updated_date date NOT NULL,
                                  CONSTRAINT support_diagnosis_pk PRIMARY KEY (id)
);
-- public.service_status definition
-- Drop table
-- DROP TABLE public.service_status;
CREATE TABLE public.service_status (
                                       id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       name_status varchar NOT NULL,
                                       description varchar NOT NULL,
                                       created_date date NOT NULL,
                                       updated_date date NOT NULL,
                                       "uuid" uuid NOT NULL,
                                       active bool NOT NULL,
                                       CONSTRAINT service_status_pk PRIMARY KEY (id)
);
-- public.type_service definition
-- Drop table
-- DROP TABLE public.type_service;
CREATE TABLE public.type_service (
                                     id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     description varchar NOT NULL,
                                     sla_hours int4 NOT NULL,
                                     created_date date NOT NULL,
                                     updated_date date NOT NULL,
                                     "uuid" uuid NOT NULL,
                                     active bool NOT NULL,
                                     CONSTRAINT sla_pk PRIMARY KEY (id)
);
-- public.support_tickets definition
-- Drop table
-- DROP TABLE public.support_tickets;
CREATE TABLE public.support_tickets (
                                        id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        num_ticket int8 NOT NULL,
                                        device_characteristics varchar NOT NULL,
                                        repair_description varchar NOT NULL,
                                        ticket_detail varchar NOT NULL,
                                        estimate_date date NOT NULL,
                                        end_date date NULL,
                                        created_date date NOT NULL,
                                        updated_date date NOT NULL,
                                        service_status_id int4 NOT NULL,
                                        device_type_id int4 NOT NULL,
                                        type_service_id int4 NOT NULL,
                                        diagnosis_id int4 NOT NULL,
                                        client_uuid uuid NULL,
                                        technical_uuid uuid NULL,
                                        purchase_uuid uuid NULL,
                                        "uuid" uuid NOT NULL,
                                        CONSTRAINT support_tickets_pk PRIMARY KEY (id),
                                        CONSTRAINT support_tickets_device_type_fk FOREIGN KEY (device_type_id) REFERENCES public.device_type(id),
                                        CONSTRAINT support_tickets_service_status_fk FOREIGN KEY (service_status_id) REFERENCES public.service_status(id),
                                        CONSTRAINT support_tickets_support_diagnosis_fk FOREIGN KEY (diagnosis_id) REFERENCES public.diagnosis(id),
                                        CONSTRAINT support_tickets_type_service_fk FOREIGN KEY (type_service_id) REFERENCES public.type_service(id)
);
-- public.evidence definition
-- Drop table
-- DROP TABLE public.evidence;
CREATE TABLE public.evidence (
                                 id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 route varchar NOT NULL,
                                 created_date date NOT NULL,
                                 updated_date date NOT NULL,
                                 "uuid" uuid NOT NULL,
                                 support_tickets_id int4 NOT NULL,
                                 CONSTRAINT evidence_pk PRIMARY KEY (id),
                                 CONSTRAINT evidence_support_tickets_fk FOREIGN KEY (support_tickets_id) REFERENCES public.support_tickets(id)
);